package views;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.nhan_khau;
import models.so_ho_khau;


public class NhanKhauManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanKhauManagePanel
     */
    private JFrame parentJFrame;
    private DefaultTableModel dtm;
private List<nhan_khau> ds_nhankhau;
    int index=-1;
    public NhanKhauManagePanel(JFrame parentFrame) throws ClassNotFoundException {
        this.parentJFrame = parentFrame;
        initComponents();
        tblNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanKhauMouseClicked(evt);
            }
        });
        //combobox giới tính
        jcbbGioiTinh.addItem("Nam");
        jcbbGioiTinh.addItem("Nữ");
        jcbbGioiTinh.addItem("Không");
        //combobox thành tích
        jcbbThanhTich.addItem("Học sinh giỏi");
        jcbbThanhTich.addItem("Học sinh khá");
        jcbbThanhTich.addItem("Khác");
        //combobox quan hệ với chủ hộ
        jcbbQuanHe.addItem("Chủ hộ");
        jcbbQuanHe.addItem("Vợ");
        jcbbQuanHe.addItem("Chồng");
        jcbbQuanHe.addItem("Con");
        jcbbQuanHe.addItem("Anh");
        jcbbQuanHe.addItem("Em");
        jcbbQuanHe.addItem("Bố");
        jcbbQuanHe.addItem("Mẹ");
        //combobox mã hộ khẩu
        try{
            for(so_ho_khau hokhau : controllers.HoKhauController.get_hokhau()){
                jcbbHoKhau.addItem(hokhau.getID()+"");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(parentJFrame, "Khong the ket noi csdl","Error",JOptionPane.ERROR_MESSAGE);
        }
        dtm = (DefaultTableModel) tblNhanKhau.getModel();
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnThem.setEnabled(true);
        Load("");
    }
    public void Load(String s) throws ClassNotFoundException{
        dtm.setRowCount(0);
        try {
            ds_nhankhau = controllers.NhanKhauController.get_nhankhau(s);
            for (nhan_khau nhankhau : ds_nhankhau) {
                dtm.addRow(new Object[]{nhankhau.getID(),nhankhau.getHoTen(),nhankhau.getNgaysinh().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")).toString(),nhankhau.getGioiTinh(),nhankhau.getDiachiThuongTru()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(parentJFrame, "Khong the ket noi csdl","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void Reset(){
        jtfNgaySinh.setText("");
        jtfNgheNghiep.setText("");
        jtfNguyenQuan.setText("");
        jtfThuongTru.setText("");
        jtfSearch.setText("");
        jtfCCCD.setText("");
        jtfHoTen.setText("");
        jcbbGioiTinh.setSelectedIndex(0);
        jcbbHoKhau.setSelectedIndex(0);
        jcbbQuanHe.setSelectedIndex(0);
        jcbbThanhTich.setSelectedIndex(0);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnThem.setEnabled(true);
        index = -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSearch = new javax.swing.JTextField();
        jtbNhanKhau = new javax.swing.JScrollPane();
        tblNhanKhau = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNguyenQuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfNgaySinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbbGioiTinh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfThuongTru = new javax.swing.JTextField();
        jcbbHoKhau = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcbbQuanHe = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jtfCCCD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfNgheNghiep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jcbbThanhTich = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        add(jtfSearch);
        jtfSearch.setBounds(135, 434, 210, 30);

        jtbNhanKhau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtbNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbNhanKhauMouseClicked(evt);
            }
        });

        tblNhanKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblNhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbNhanKhau.setViewportView(tblNhanKhau);
        if (tblNhanKhau.getColumnModel().getColumnCount() > 0) {
            tblNhanKhau.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jtbNhanKhau);
        jtbNhanKhau.setBounds(0, 123, 740, 292);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nhập ID nhân khẩu");
        add(jLabel2);
        jLabel2.setBounds(12, 433, 120, 30);

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem);
        btnTimKiem.setBounds(405, 433, 90, 30);

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(750, 160, 90, 30);

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem);
        btnThem.setBounds(750, 40, 90, 30);

        btnSua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(750, 100, 90, 30);

        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi);
        btnLamMoi.setBounds(750, 210, 90, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Họ tên:");
        add(jLabel1);
        jLabel1.setBounds(12, 16, 50, 17);

        jtfHoTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(jtfHoTen);
        jtfHoTen.setBounds(70, 13, 179, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nguyên quán: ");
        add(jLabel3);
        jLabel3.setBounds(267, 16, 90, 17);

        jtfNguyenQuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(jtfNguyenQuan);
        jtfNguyenQuan.setBounds(361, 13, 190, 23);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã hộ khẩu:");
        add(jLabel5);
        jLabel5.setBounds(12, 52, 80, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("CCCD:");
        add(jLabel8);
        jLabel8.setBounds(12, 85, 60, 17);

        jtfNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(jtfNgaySinh);
        jtfNgaySinh.setBounds(641, 13, 100, 23);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Giới tính");
        add(jLabel9);
        jLabel9.setBounds(195, 85, 60, 17);

        add(jcbbGioiTinh);
        jcbbGioiTinh.setBounds(255, 84, 59, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Thường trú:");
        add(jLabel4);
        jLabel4.setBounds(177, 52, 90, 17);

        jtfThuongTru.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(jtfThuongTru);
        jtfThuongTru.setBounds(263, 49, 254, 23);

        add(jcbbHoKhau);
        jcbbHoKhau.setBounds(100, 51, 59, 22);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Quan hệ với chủ hộ:");
        add(jLabel10);
        jLabel10.setBounds(332, 85, 130, 17);

        add(jcbbQuanHe);
        jcbbQuanHe.setBounds(458, 84, 70, 22);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Ngày sinh:");
        add(jLabel11);
        jLabel11.setBounds(569, 16, 70, 17);

        jtfCCCD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(jtfCCCD);
        jtfCCCD.setBounds(70, 82, 113, 23);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Nghề nghiệp:");
        add(jLabel12);
        jLabel12.setBounds(555, 52, 80, 17);

        jtfNgheNghiep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(jtfNgheNghiep);
        jtfNgheNghiep.setBounds(641, 49, 100, 23);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Thành tích:");
        add(jLabel13);
        jLabel13.setBounds(560, 90, 70, 17);

        add(jcbbThanhTich);
        jcbbThanhTich.setBounds(640, 90, 100, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            Load(jtfSearch.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NhanKhauManagePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            controllers.NhanKhauController.deleteNhanKhau(ds_nhankhau.get(index).getID());
            Load("");
            Reset();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(parentJFrame, "Không thể xóa nhân khẩu này","Error",JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(parentJFrame, "Không thể xóa nhân khẩu này","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String HoTen = jtfHoTen.getText().toString();
        String NguyenQuan  = jtfNguyenQuan.getText().toString();
        String DiaChiThuongTru  = jtfThuongTru.getText().toString();
        int ID_HoKhau  = Integer.parseInt(jcbbHoKhau.getSelectedItem().toString());
        String GioiTinh  = jcbbGioiTinh.getSelectedItem().toString();
        String quanhe  = jcbbQuanHe.getSelectedItem().toString();
        LocalDate NgaySinh = null;
        try{
            NgaySinh  = LocalDate.parse(jtfNgaySinh.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(parentJFrame, "Ngày sinh phải nhập đúng định dạng dd/MM/yyyy","Error",JOptionPane.ERROR_MESSAGE);
        }
        String NgheNghiep  = jtfNgheNghiep.getText().toString();
        String ThanhTich  = jcbbThanhTich.getSelectedItem().toString();
        String CCCD = jtfCCCD.getText().toString();
        if(HoTen.equals("")||CCCD.equals("")||NguyenQuan.equals("")||DiaChiThuongTru.equals("")||(ID_HoKhau+"").equals("")||GioiTinh.equals("")||quanhe.equals("")||NgaySinh.equals("")||NgheNghiep.equals("")||ThanhTich.equals("")){
            JOptionPane.showMessageDialog(parentJFrame, "Vui lòng nhập đầy đủ thông tin","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            nhan_khau nhankhau = new nhan_khau();
            nhankhau.setCCCD(CCCD);nhankhau.setDiachiThuongTru(DiaChiThuongTru);
            nhankhau.setGioiTinh(GioiTinh);nhankhau.setHoTen(HoTen);
            nhankhau.setNgaysinh(NgaySinh);nhankhau.setIDHoKhau(ID_HoKhau);
            nhankhau.setNgheNghiep(NgheNghiep);nhankhau.setNguyenQuan(NguyenQuan);
            nhankhau.setQuanhevoichuho(quanhe);nhankhau.setThanhTich(ThanhTich);
            try {
                controllers.NhanKhauController.addNhanKhau(nhankhau);
                Load("");
                Reset();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(parentJFrame, "Không thể thêm nhân khẩu","Error",JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(parentJFrame, "Không thể thêm nhân khẩu","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       String HoTen = jtfHoTen.getText().toString();
        String NguyenQuan  = jtfNguyenQuan.getText().toString();
        String DiaChiThuongTru  = jtfThuongTru.getText().toString();
        int ID_HoKhau  = Integer.parseInt(jcbbHoKhau.getSelectedItem().toString());
        String GioiTinh  = jcbbGioiTinh.getSelectedItem().toString();
        String quanhe  = jcbbQuanHe.getSelectedItem().toString();
        LocalDate NgaySinh = null;
        try{
            NgaySinh  = LocalDate.parse(jtfNgaySinh.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(parentJFrame, "Ngày sinh phải nhập đúng định dạng dd/MM/yyyy","Error",JOptionPane.ERROR_MESSAGE);
        }
        String NgheNghiep  = jtfNgheNghiep.getText().toString();
        String ThanhTich  = jcbbThanhTich.getSelectedItem().toString();
        String CCCD = jtfCCCD.getText().toString();
        if(HoTen.equals("")||CCCD.equals("")||NguyenQuan.equals("")||DiaChiThuongTru.equals("")||(ID_HoKhau+"").equals("")||GioiTinh.equals("")||quanhe.equals("")||NgaySinh.equals("")||NgheNghiep.equals("")||ThanhTich.equals("")){
            JOptionPane.showMessageDialog(parentJFrame, "Vui lòng nhập đầy đủ thông tin","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            nhan_khau nhankhau = new nhan_khau();
            nhankhau.setID(ds_nhankhau.get(index).getID());
            nhankhau.setCCCD(CCCD);nhankhau.setDiachiThuongTru(DiaChiThuongTru);
            nhankhau.setGioiTinh(GioiTinh);nhankhau.setHoTen(HoTen);
            nhankhau.setNgaysinh(NgaySinh);nhankhau.setIDHoKhau(ID_HoKhau);
            nhankhau.setNgheNghiep(NgheNghiep);nhankhau.setNguyenQuan(NguyenQuan);
            nhankhau.setQuanhevoichuho(quanhe);nhankhau.setThanhTich(ThanhTich);
            try {
                controllers.NhanKhauController.updateNhanKhau(nhankhau);
                Load("");
                Reset();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(parentJFrame, "Không thể sửa nhân khẩu","Error",JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(parentJFrame, "Không thể sửa nhân khẩu","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        Reset();
        
    }//GEN-LAST:event_btnLamMoiActionPerformed
 private void tblNhanKhauMouseClicked(java.awt.event.MouseEvent evt){
        index = tblNhanKhau.getSelectedRow();
        nhan_khau nhankhau = ds_nhankhau.get(index);
        jtfHoTen.setText(nhankhau.getHoTen());
        jtfNguyenQuan.setText(nhankhau.getNguyenQuan());
        jtfThuongTru.setText(nhankhau.getNguyenQuan());
        jcbbHoKhau.setSelectedItem(nhankhau.getIDHoKhau()+"");
        jcbbGioiTinh.setSelectedItem(nhankhau.getGioiTinh());
        jcbbQuanHe.setSelectedItem(nhankhau.getQuanhevoichuho());
        jtfNgaySinh.setText(nhankhau.getNgaysinh().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        jtfNgheNghiep.setText(nhankhau.getNgheNghiep().toString());
        jcbbThanhTich.setSelectedItem(nhankhau.getThanhTich());
        jtfCCCD.setText(nhankhau.getCCCD().toString());
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnThem.setEnabled(false);
}
    private void jtbNhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbNhanKhauMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtbNhanKhauMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbbGioiTinh;
    private javax.swing.JComboBox<String> jcbbHoKhau;
    private javax.swing.JComboBox<String> jcbbQuanHe;
    private javax.swing.JComboBox<String> jcbbThanhTich;
    private javax.swing.JScrollPane jtbNhanKhau;
    private javax.swing.JTextField jtfCCCD;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfNgaySinh;
    private javax.swing.JTextField jtfNgheNghiep;
    private javax.swing.JTextField jtfNguyenQuan;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfThuongTru;
    private javax.swing.JTable tblNhanKhau;
    // End of variables declaration//GEN-END:variables
}
