/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.de_muc_phan_thuong;
import models.nhan_khau;

public class TraoQuaPanel extends javax.swing.JPanel {
    /**
     * Creates new form TraoQuaPanel
     */
    private JFrame parentFrame;
    private DefaultTableModel dtm;
    private List<nhan_khau> ds_nhankhau;
    private List<de_muc_phan_thuong> ds_qua;
    private int flag = 0;
    public TraoQuaPanel(JFrame parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        dtm = (DefaultTableModel) tbl.getModel();
        try {
            ds_qua = controllers.QuaTangController.getPhanThuong();
            for (de_muc_phan_thuong qua  : ds_qua) {
                cbbPhanQua.addItem(qua.getTenPhanThuong());
            }
            flag = 1;
        } catch (SQLException ex) {
            Logger.getLogger(TraoQuaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TraoQuaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }public void Load(int t1, int t2, String ThanhTich ) throws ClassNotFoundException{
        dtm.setRowCount(0);       
        try {
            ds_nhankhau = controllers.NhanKhauController.get_nhankhau(t1,t2,ThanhTich);
            for (nhan_khau nk: ds_nhankhau) {
                dtm.addRow(new Object[]{nk.getID(), nk.getHoTen(),nk.getNgaysinh().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),nk.getThanhTich()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(parentFrame, "Khong the ket noi csdl","Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDangThuong = new javax.swing.JTextField();
        jtfTuoi2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbThanhTich = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbPhanQua = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfTuoi1 = new javax.swing.JTextField();
        jtfGiaTri = new javax.swing.JTextField();
        BtTraoQua = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtfTongnguoi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfTien = new javax.swing.JTextField();
        btLoc = new javax.swing.JButton();

        setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Nhân Khẩu", "Họ Tên", "Ngày Sinh", "Thành Tích"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 180, 850, 220);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Điều kiện trao quà:");
        add(jLabel1);
        jLabel1.setBounds(60, 10, 200, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Phần quà: ");
        add(jLabel2);
        jLabel2.setBounds(580, 10, 120, 30);

        jtfDangThuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtfDangThuong.setEnabled(false);
        add(jtfDangThuong);
        jtfDangThuong.setBounds(610, 123, 150, 20);

        jtfTuoi2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jtfTuoi2);
        jtfTuoi2.setBounds(230, 70, 40, 23);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Đến:");
        add(jLabel4);
        jLabel4.setBounds(180, 70, 40, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Thành Tích:");
        add(jLabel5);
        jLabel5.setBounds(20, 110, 90, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Từ:");
        add(jLabel3);
        jLabel3.setBounds(90, 70, 30, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Độ tuổi:");
        add(jLabel6);
        jLabel6.setBounds(20, 70, 90, 17);

        cbbThanhTich.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbbThanhTich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không", "Học Sinh Giỏi", "Học Sinh Khá", " " }));
        add(cbbThanhTich);
        cbbThanhTich.setBounds(120, 110, 150, 23);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Dạng thưởng:");
        add(jLabel7);
        jLabel7.setBounds(500, 120, 100, 17);

        cbbPhanQua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbbPhanQua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPhanQuaItemStateChanged(evt);
            }
        });
        add(cbbPhanQua);
        cbbPhanQua.setBounds(610, 60, 150, 25);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Tên Phần Quà:");
        add(jLabel8);
        jLabel8.setBounds(500, 60, 100, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Giá trị:");
        add(jLabel9);
        jLabel9.setBounds(500, 90, 60, 17);

        jtfTuoi1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtfTuoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTuoi1ActionPerformed(evt);
            }
        });
        add(jtfTuoi1);
        jtfTuoi1.setBounds(130, 70, 40, 23);

        jtfGiaTri.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtfGiaTri.setEnabled(false);
        add(jtfGiaTri);
        jtfGiaTri.setBounds(610, 90, 150, 23);

        BtTraoQua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BtTraoQua.setText("Trao Quà");
        BtTraoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTraoQuaActionPerformed(evt);
            }
        });
        add(BtTraoQua);
        BtTraoQua.setBounds(380, 430, 90, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Tổng số người đủ điều kiện trao thưởng: ");
        add(jLabel10);
        jLabel10.setBounds(10, 410, 240, 17);

        jtfTongnguoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfTongnguoi.setText("0");
        jtfTongnguoi.setEnabled(false);
        add(jtfTongnguoi);
        jtfTongnguoi.setBounds(250, 410, 70, 23);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Số tiền phải chi: ");
        add(jLabel11);
        jLabel11.setBounds(590, 410, 100, 17);

        jtfTien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfTien.setEnabled(false);
        add(jtfTien);
        jtfTien.setBounds(700, 410, 70, 23);

        btLoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btLoc.setText("Lọc");
        btLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocActionPerformed(evt);
            }
        });
        add(btLoc);
        btLoc.setBounds(100, 150, 90, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTuoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTuoi1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfTuoi1ActionPerformed

    private void btLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocActionPerformed
        // TODO add your handling code here:
        int t1,t2;
        
        if(jtfTuoi1.getText()=="" &&jtfTuoi2.getText()==""){
            JOptionPane.showMessageDialog(parentFrame, "bạn cần điền đầy đủ thông tin");
        }
        else{
            try{
                t1=Integer.parseInt(jtfTuoi1.getText());
                t2=Integer.parseInt(jtfTuoi2.getText());
                String s=cbbThanhTich.getSelectedItem().toString();
                Load(t1, t2, s);
                jtfTongnguoi.setText(""+ds_nhankhau.size()+"");
            }
            catch(NumberFormatException E){
                JOptionPane.showMessageDialog(parentFrame, "Bạn cần nhập số nguyên!");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TraoQuaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_btLocActionPerformed

    private void cbbPhanQuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPhanQuaItemStateChanged
        if(flag==1){
            if(jtfTongnguoi.getText()!=""){
                int index = cbbPhanQua.getSelectedIndex();
                jtfGiaTri.setText(""+ds_qua.get(index).getGiaTri()+"");
                jtfDangThuong.setText(ds_qua.get(index).getDangThuong());
                jtfTien.setText(""+Double.parseDouble(jtfTongnguoi.getText())*Double.parseDouble(jtfGiaTri.getText())+"");
            }
            else{
                JOptionPane.showMessageDialog(parentFrame, "Ban cần lọc danh sách người nhận thưởng trước");
            }
        }
    }//GEN-LAST:event_cbbPhanQuaItemStateChanged

    private void BtTraoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTraoQuaActionPerformed
        if (JOptionPane.showConfirmDialog(parentFrame, "Bạn có chắc muốn trao quà không", "Confirm", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                controllers.TraoQuaController.addTraoQua(ds_nhankhau, Double.parseDouble(jtfGiaTri.getText()), cbbPhanQua.getSelectedItem().toString());
            } catch (SQLException ex) {
                Logger.getLogger(TraoQuaPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TraoQuaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtTraoQuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtTraoQua;
    private javax.swing.JButton btLoc;
    private javax.swing.JComboBox<String> cbbPhanQua;
    private javax.swing.JComboBox<String> cbbThanhTich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfDangThuong;
    private javax.swing.JTextField jtfGiaTri;
    private javax.swing.JTextField jtfTien;
    private javax.swing.JTextField jtfTongnguoi;
    private javax.swing.JTextField jtfTuoi1;
    private javax.swing.JTextField jtfTuoi2;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
