/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.nhan_khau;

public class HoKhauFrame extends javax.swing.JFrame {

    /**
     * Creates new form HoKhauFrame
     */
    private DefaultTableModel dtm;
    private JFrame parentJFrame;
    public HoKhauFrame(String s,JFrame parentJFrame) throws ClassNotFoundException {
        initComponents();
        tblNhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Quan hệ với chủ hộ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false,false
            };
        public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        this.parentJFrame = parentJFrame;
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close();
            }           
        });
        lblThongTin.setText("DANH SÁCH NHÂN KHẨU CỦA HỘ "+s);
        dtm = (DefaultTableModel) tblNhanKhau.getModel();
        Load(s);
    }

    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            dispose();
        }
    }
    public void Load(String s) throws ClassNotFoundException{
        dtm.setRowCount(0);
        try {
            List<nhan_khau> ds_nhankhau = controllers.NhanKhauController.get_nhankhau1(s);
            if(s.equals("1")) ds_nhankhau.add(1, ts);
            for (nhan_khau nhankhau : ds_nhankhau) {
                dtm.addRow(new Object[]{nhankhau.getID(),nhankhau.getHoTen(),nhankhau.getNgaysinh().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")).toString(),nhankhau.getGioiTinh(),nhankhau.getDiachiThuongTru(),nhankhau.getQuanhevoichuho()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Khong the ket noi csdl","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanKhau = new javax.swing.JTable();
        lblThongTin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Danh Sách Nhân Khẩu Trong Hộ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 100));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tblNhanKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblNhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNhanKhau);

        lblThongTin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongTin.setText("lblThongTin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private nhan_khau ts = new nhan_khau(1000,"Nguyễn Ngọc Trường Sơn","Nam Định","Nam Định",1,"036201012223","Nam","Chồng",LocalDate.of(2001,Month.APRIL, 18),"Sinh Viên","Học sinh giỏi");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JTable tblNhanKhau;
    // End of variables declaration//GEN-END:variables
}
